- name: install nginx and git
  hosts: local
  connection: local
  tasks:
  - name: install nginx and git
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed


    loop:
    - nginx
    - git

  