- name: check the value is greter then or not
  hosts: local
  connection: local
  vars:
    my_number: 50
  tasks:
  - name: print if the number is greater than 10
    ansible.builtin.debug:
       msg: "the number {{ my_number }} is greater then 10"
    when: my_number > 10