  - name: create ec2 and r53 
    hosts: local
    connection: local
    vars:
      sg_id: sg-0a45058bd6da2342c
      subnets: subnet-0e2183fb4245ac220
      ami_id: ami-09c813fb71547fc4f
      instance_type: t3.micro
      instances:
      - mysql
      - backend
      - frontend
    
    tasks:
    - name: install python libraries
      ansible.builtin.package:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - boto3
      - botocore

    - name: creting ec2 instances
      amazon.aws.ec2_instance:
         name: "{{ item }}"
         security_group: "{{ sg_id }}"
         subnet_id: "{{ subnets }}"
         image_id: "{{ ami_id }}"
         instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"


