- name: print the datatypes
  hosts: local
  connection: local
  vars:
    course_name: "devops with aws"
    duration: 120
    topics:
    - linux
    - shell script
    - ansible
    - jenkins
    live: true
    tools:
     ci: jjj
     jenkins: fff
     sonarqube: rrr

  tasks:
  - name: print all variables
    ansible.builtin.debug:
      msg: "course is {{ course_name }}, duration is {{ duration }}, topics covered are {{ topics }}, is it live?: {{ live }}, tools covered {{ tools }}"