- name: filters
  hosts: local  
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "hello {{ person | default ('Ramesh') }}"

  - name: convert string to list
    vars:
     fruits: "apple, orange, banana"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (',')}}"