- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variabke
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: devops with aws
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info :: {{ course | dict2items }}"

  - name: conver list to map
    vars:
     course:
     - {'key': 'name', 'value': 'devops with aws'}
     - {'key': 'duration', 'value': 120}
     - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
       msg: "course info :: {{ course | items2dict }}"



  - name: max and min numbers
    vars:
      numbers: [1,30,48,55,87,99,76677]
    ansible.builtin.debug:
        msg: "min is: {{ numbers | min }}  max is {{ numbers | max }}"
