- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variabke
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: devops with aws
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info :: {{ course | dict2items }}"