- name: filters
  hosts: local
  connection: local
  tasks:
  - name: convering string to list
    vars:
     fruits: "apple, orange, banana"
    ansible.builtin.debug:
      msg: fruits are {{ fruits | split (',') }}
  

  - name: converting maps to list
    vars:
     course:
      name: devops with aws
      duration: 120 hrs
      trainer: sivakumar
    ansible.builtin.debug:
      msg: " course info :: {{ course | dict2items }}"


    