- name: filters
  hosts: local  
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "hello {{ person | default ('Ramesh') }}"

  - name: convert string to list
    vars:
     fruits: "apple, orange, banana"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (',')}}"
    

  - name: convert list in to map
    vars:
     course:
       name: ansible  
       duration: 10hrs
       trainer: sivakumar
    ansible.builtin.debug:
  
      msg: "course info: {{ course | dict2items }}"

  - name: convert maps into list
    vars: 
     course:
     - { 'key': 'name', 'value': 'ansible'}
    ansible.builtin.debug:
      msg: "course info : {{ course | items2dict}}