- name: instlaling servers
  hosts: local
  connection: local
  tasks:
   - name: installing servers
     ansible.builtin.package:
        name: "{{ item }}"
        state: installed
     loop:
     - nginx
     - git
     - gcc