- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print the names using loops
    ansible.builtin.debug:
       msg: "{{ item }}"
    


    loop:
    - venkatesh
    - ramesh
    - suresh