- name: instlaling servers
  hosts: local
  connection: local
  tasks:
  - name: installing serveres
    ansible.builtin.package:
       name: "{{ item }}"
       state: installed
    loop:
    - nginx
    - mysql
    - git
    - zip