- name: instlaling servers
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing serveres
    ansible.builtin.package:
       name: "{{ item }}"
       state: installed
    loop:

    - { name: 'git', state: 'absent'}
    - { name: 'nginx', state: 'present'}
    - { name: 'gcc', state: 'present'}
    - { name: 'zip', state: 'present'}