- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable mysql-server
    ansible.builtin.service:
       name: mysqld
       state: started
       enabled: yes
  - name: root password setting up and connecto to mysql
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.daws17s.online
    register: mysql_info
  

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
