- name: installing mysql
  hosts: mysql
  become: yes

  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL
  - name: installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable mysql-server
    ansible.builtin.service:
       name: mysqld
       state: started
       enabled: yes
  - name:  connecting  to mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.daws17s.online
    register: mysql_info
    ignore_errors: true

  

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"


  - name: setting up the rootpassword
    ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1 "
    when: mysql_info.failed is true
