- name: shell vs command
  hosts: local 
  connection: local
  tasks:
  - name: exectute ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.log

  - name: execute ls command in command module
    ansible.builtin.command: lsss -ltrsss
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"

     