- name: variables
  hosts: local 
  connection: local 
  vars:
    COURSE: "devops with aws"
    DURATION: 120HRS
    TRAINER: sivakumar
  tasks:
  - name: printing the variables  
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration {{ DURATION }}  trainer is {{ TRAINER }}"

