- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120hrs
    TRAINER: sivakumar
  tasks:
  - name: print the variables
    vars:
     COURSE: ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
      