- name: taking variables from the prompt
  hosts: local  
  connection: local

  tasks:
  - name: variable names took from the prompts
    ansible.builtin.debug:
     msg: course is {{ COURSE }}, duration is {{ DURATION }}, faculty is {{ FACULTY }}