- name: variables
  hosts: local 
  connection: local 
 
  tasks:
  - name: printing the variables  
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration {{ DURATION }}  trainer is {{ FACULTY }}"